<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Beli</name>
   <tag></tag>
   <elementGuidId>54f654ae-1b9a-4256-aefd-630604d65043</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='beli']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#beli</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>944c390f-b3c0-4a15-8de6-b7534da704fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>beli</value>
      <webElementGuid>2a401f63-4c4b-48d6-9c8b-90fc8dc2e069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button__tertiary button-order</value>
      <webElementGuid>47a03233-edaf-4723-b1a4-687ee4dce487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2120482d-b4d8-47be-b037-49fa8d9a464f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addToCart2(553,104)</value>
      <webElementGuid>4cf1896f-022e-4a99-84ce-11d717c016fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beli</value>
      <webElementGuid>7fcbf027-7367-4b17-a524-919a89d129ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_beli&quot;)/button[@id=&quot;beli&quot;]</value>
      <webElementGuid>d600503d-92be-47b6-a93e-5e8fa7f8534d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='beli']</value>
      <webElementGuid>a3c3305e-2424-4364-bedd-51d2cecd7155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='btn_beli']/button</value>
      <webElementGuid>5188be3a-f636-4afd-987a-7f4c371fa717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/button</value>
      <webElementGuid>8e6aef7d-e13a-4d7b-a314-b8ac423ae1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'beli' and @type = 'button' and (text() = 'Beli' or . = 'Beli')]</value>
      <webElementGuid>eb0edd49-f13c-455c-b1a1-c5a0ced1b9f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
