<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Masuk_icon icon-cart</name>
   <tag></tag>
   <elementGuidId>9a660719-7273-4234-8421-ae2e449f3e50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.icon.icon-cart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2e79dc52-2964-4fdd-b17c-c5925c323c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon icon-cart</value>
      <webElementGuid>1f1381f9-c62a-419f-a047-62db7947b03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js csstransitions&quot;]/body[1]/div[@class=&quot;page-wrapper&quot;]/header[@class=&quot;header header--fixed&quot;]/div[@class=&quot;container clearfix&quot;]/div[@class=&quot;row col-offset-fluid clearfix&quot;]/div[@class=&quot;col-xs-7 col-lg-9&quot;]/div[@class=&quot;header__menu clearfix&quot;]/div[@class=&quot;header__item pull-right&quot;]/a[@class=&quot;header__icon&quot;]/span[@class=&quot;icon icon-cart&quot;]</value>
      <webElementGuid>ceee7875-01dc-418c-9c1b-739c7dfe4cb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>4341c80e-a0b9-4f20-9384-785874f09e30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
