<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Masuk</name>
   <tag></tag>
   <elementGuidId>0f6d7e5d-0ba6-43a9-91ca-9c66741db351</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Masuk')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.header__link.header__link--login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e54195eb-6bc8-4441-bda6-7c327623ec17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://my.kontan.co.id/?uri=https://store.kontan.co.id/auth/user_login&amp;_ga=2.11443005.841837125.1709175949-50423732.1709175949</value>
      <webElementGuid>c35553c1-9daa-4f52-b22d-adf58b01d994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header__link header__link--login</value>
      <webElementGuid>133b9224-38f2-4bd2-b263-2ba22631ef98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>23e80e31-6b92-432b-8852-065e52a5f6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js csstransitions&quot;]/body[1]/div[@class=&quot;page-wrapper&quot;]/header[@class=&quot;header header--fixed&quot;]/div[@class=&quot;container clearfix&quot;]/div[@class=&quot;row col-offset-fluid clearfix&quot;]/div[@class=&quot;col-xs-7 col-lg-9&quot;]/div[@class=&quot;header__menu clearfix&quot;]/div[@class=&quot;header__item pull-right&quot;]/div[@class=&quot;mobile-hide&quot;]/a[@class=&quot;header__link header__link--login&quot;]</value>
      <webElementGuid>c49877d0-0081-48da-8843-cacb0d132016</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Masuk')]</value>
      <webElementGuid>b82b95e1-09a0-44ce-bb59-4c1981350c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://my.kontan.co.id/?uri=https://store.kontan.co.id/auth/user_login&amp;_ga=2.11443005.841837125.1709175949-50423732.1709175949')]</value>
      <webElementGuid>a2f89492-f583-4bbf-806a-eec1a6b7c809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>94b96434-94da-4b2a-b659-273081b6206f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://my.kontan.co.id/?uri=https://store.kontan.co.id/auth/user_login&amp;_ga=2.11443005.841837125.1709175949-50423732.1709175949' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>972cc7dd-b68c-46c7-aed1-6137e6f497e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
