<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Langganan Business Insight_lozad</name>
   <tag></tag>
   <elementGuidId>0f98fb21-44f0-4830-b837-d83e2ef98201</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='test-load']/ul/li[2]/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3cd27ac4-358c-4ff6-af43-97d8bef8f70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lozad</value>
      <webElementGuid>373e6763-0276-4aaa-ae17-182baa2ecc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://fs-media.kontan.co.id/kstore/upload/brand_images/brand_images_30122108391800.jpg</value>
      <webElementGuid>97e6679e-ca1c-433f-8aad-d167122edad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>KONTAN DIGITAL PREMIUM ACCESS</value>
      <webElementGuid>0ab52bdf-025e-422b-97ea-6d14333c11b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://fs-media.kontan.co.id/kstore/upload/brand_images/brand_images_30122108391800.jpg</value>
      <webElementGuid>4d048f25-cd49-409e-9c72-03e9bbe38de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>76c28a20-3b88-474d-82af-160d74b313d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;test-load&quot;)/ul[@class=&quot;book__wrap&quot;]/li[@class=&quot;book__item&quot;]/div[@class=&quot;book__box&quot;]/div[@class=&quot;book__img&quot;]/a[@class=&quot;book__link&quot;]/img[@class=&quot;lozad&quot;]</value>
      <webElementGuid>21554ac5-2d12-4778-95d1-0c5a1c50ab40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='test-load']/ul/li[2]/div/div/a/img</value>
      <webElementGuid>befa5b72-7f67-4a53-bbf9-f71ed35efcfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='KONTAN DIGITAL PREMIUM ACCESS']</value>
      <webElementGuid>6b923b26-6199-4915-9819-5f2167c79771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/a/img</value>
      <webElementGuid>b1376efe-ba47-4ca1-9914-c509b472d20f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'KONTAN DIGITAL PREMIUM ACCESS' and @src = 'https://fs-media.kontan.co.id/kstore/upload/brand_images/brand_images_30122108391800.jpg']</value>
      <webElementGuid>9d89e588-2e33-4e1a-99a8-a94e45842a7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
